version: "3"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/home/node/app

  web:
    build: ./web
    ports:
      - "3001:3000"
    volumes:
      - ./web:/home/node/app

  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_DATABASE: nest
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456

volumes:
  mongodb_data:
    driver: local
